name: projeto_final
description: Projeto do primeiro curso de WebAPI da Formação Flutter
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uuid: ^3.0.6
  google_fonts: ^2.1.0
  image_picker: ^0.8.4+4
  flutter_lints: ^2.0.0
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
